// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhDnXpXqoimE0MTgmQr76vik8OI7tB-c',
    appId: '1:1027854753912:web:46f9f5693d333118774d8d',
    messagingSenderId: '1027854753912',
    projectId: 'doctor-appointment-app-5037f',
    authDomain: 'doctor-appointment-app-5037f.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-5037f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_EU-GtJ9vF6XgdTJbBjflZrV23DwVn0M',
    appId: '1:1027854753912:android:8e30bdf4e22657d5774d8d',
    messagingSenderId: '1027854753912',
    projectId: 'doctor-appointment-app-5037f',
    storageBucket: 'doctor-appointment-app-5037f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa_nMRHhO8MmrFFuWi6Dv3hk0ykZsSK7s',
    appId: '1:1027854753912:ios:6096c05e601ec994774d8d',
    messagingSenderId: '1027854753912',
    projectId: 'doctor-appointment-app-5037f',
    storageBucket: 'doctor-appointment-app-5037f.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa_nMRHhO8MmrFFuWi6Dv3hk0ykZsSK7s',
    appId: '1:1027854753912:ios:6096c05e601ec994774d8d',
    messagingSenderId: '1027854753912',
    projectId: 'doctor-appointment-app-5037f',
    storageBucket: 'doctor-appointment-app-5037f.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzhDnXpXqoimE0MTgmQr76vik8OI7tB-c',
    appId: '1:1027854753912:web:438c92f1918002c8774d8d',
    messagingSenderId: '1027854753912',
    projectId: 'doctor-appointment-app-5037f',
    authDomain: 'doctor-appointment-app-5037f.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-5037f.firebasestorage.app',
  );
}
